## Setup Môi Trường



In [ ]:
#Kiểm tra GPU
!nvidia-smi

Sat Aug 14 06:39:06 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#Liên kết file này với Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


##Clone source code từ github và set-up các tài nguyên cần thiết

In [ ]:
#Truy cập đến MyDrive
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [ ]:
#Tải các file cần thiết từ github về
!git clone https://github.com/CS-UIT-AI-CLUB/CRAFT

fatal: destination path 'CRAFT' already exists and is not an empty directory.


In [ ]:
#Truy cập vào mục CRAFT
%cd CRAFT

/content/drive/MyDrive/CRAFT


In [ ]:
#Tải về các package cần thiết
#Tải về pillow phiên bản 6.2.2
!pip install pillow==6.2.2

  Using cached Pillow-6.2.2-cp37-cp37m-manylinux1_x86_64.whl (2.1 MB)
  Attempting uninstall: pillow
    Found existing installation: Pillow 2.8.2
    Uninstalling Pillow-2.8.2:
      Successfully uninstalled Pillow-2.8.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
water 0.1.dev1 requires Pillow==2.8.2, but you have pillow 6.2.2 which is incompatible.
bokeh 2.3.3 requires pillow>=7.1.0, but you have pillow 6.2.2 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [ ]:
#Tải các file cần thiết từ pytorch
#Lưu ý nếu cell báo lỗi thì nhấn lại vào cell truy cập vào thư mục CRAFT
!pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 735.3 MB 25 kB/s 
     |████████████████████████████████| 12.7 MB 154 kB/s 
     |████████████████████████████████| 25.0 MB 99 kB/s 
     |████████████████████████████████| 25.3 MB 71 kB/s 
     |████████████████████████████████| 31.2 MB 51 kB/s 
  Created wheel for Polygon3: filename=Polygon3-3.0.9.1-cp37-cp37m-linux_x86_64.whl size=102642 sha256=6346069812abcca2039195227eb724101437bc02b5cdaf249106d8d281461f24
  Stored in directory: /root/.cache/pip/wheels/0d/f3/a1/d9909fbad83c438786f3fbde79b0636c9e843107bad74baba7
Successfully built Polygon3
  Attempting uninstall: torch
    Found existing installation: torch 1.9.0+cu102
    Uninstalling torch-1.9.0+cu102:
      Successfully uninstalled torch-1.9.0+cu102
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: tor

In [ ]:
#Tải về các package cần thiết
!pip install water 

     |████████████████████████████████| 9.4 MB 6.2 MB/s 
  Created wheel for water: filename=water-0.1.dev1-py3-none-any.whl size=1845 sha256=8bf63e798230033acf526f6adf5b66a9d577f64cae417b6df6000f0c8a7342b5
  Stored in directory: /root/.cache/pip/wheels/4b/77/3c/6272eae3ae839ae94fe0b6d7ddcbd525a5c1729d2c440da4ff
  Created wheel for Pillow: filename=Pillow-2.8.2-cp37-cp37m-linux_x86_64.whl size=1043294 sha256=cdecbe4d40da33b7c43384b301e9a1b93ae2aa65cffcc448bf28b6d0873d3589
  Stored in directory: /root/.cache/pip/wheels/bf/98/61/cc6808046ba818ffe3aff2b8d699fa5493362de36301aa130d
Successfully built water Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 6.2.2
    Uninstalling Pillow-6.2.2:
      Successfully uninstalled Pillow-6.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.8.1+cu101 requires pillow>=4.1.1, but you h

In [ ]:
#Tạo các thư mục để chứa file test
!mkdir result
!mkdir results
!mkdir tested_image

mkdir: cannot create directory ‘result’: File exists
mkdir: cannot create directory ‘results’: File exists
mkdir: cannot create directory ‘tested_image’: File exists


In [ ]:
%cd /content/drive/MyDrive/CRAFT/pretrain
#Tải các file cần thiết cho training
!gdown --id 1-RM4shR-oj0cWO-9mthKZKnyF-qy1OZW -O 91.pth
!gdown --id 1wQDetvezJGp6eBVK7_yInOzZdpoD3k7j -O vgg16_bn-6c64b313.pth

/content/drive/MyDrive/CRAFT/pretrain
Permission denied: https://drive.google.com/uc?id=1-RM4shR-oj0cWO-9mthKZKnyF-qy1OZW
Maybe you need to change permission over 'Anyone with the link'?
Permission denied: https://drive.google.com/uc?id=1wQDetvezJGp6eBVK7_yInOzZdpoD3k7j
Maybe you need to change permission over 'Anyone with the link'?


##Tải dữ liệu

In [ ]:
%cd /content/drive/MyDrive
#Tải về và giải nén dữ liệu
!gdown --id 13_4EqHuOV2T2Sq_oCKFYJMqLgSCoBjHM -O train.zip
!unzip train.zip 

/content/drive/MyDrive
Downloading...
From: https://drive.google.com/uc?id=13_4EqHuOV2T2Sq_oCKFYJMqLgSCoBjHM
To: /content/drive/MyDrive/train.zip
7.86MB [00:00, 4.90MB/s]Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 61, in main
    quiet=args.quiet,
  File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 116, in download
    os.remove(tmp_file)
KeyboardInterrupt
9.57MB [00:00, 25.8MB/s]
Archive:  train.zip


In [ ]:
#Thay đổi tên của thư mục theo định dạng đúng
import os
os.rename('./train/images','./train/ch4_training_images')
os.rename('./train/labels','./train/ch4_training_localization_transcription_gt')

In [ ]:
#Thay đổi định dạng của dữ liệu
%cd /content/drive/MyDrive/train/ch4_training_localization_transcription_gt
directory = os.listdir('/content/drive/MyDrive/train/ch4_training_localization_transcription_gt')
#Thay doi ten cac file trong tep de cho no dung voi dinh dang cua CRAFT
for file in directory:
	name, ext = os.path.splitext(file)
	os.rename(file, 'gt_' + name + ext)

/content/drive/MyDrive/train/ch4_training_localization_transcription_gt


## Bắt đầu train

In [ ]:
#Vào thư mục CRAFT
%cd /content/drive/MyDrive/CRAFT

/content/drive/MyDrive/CRAFT


In [ ]:
#Tiếm hanh train du lieu
#Việc train dữ liệu sẽ diễn ra tương đối lâu, do đó bạn có thể để máy treo cho nó tự train nhé !
#Nếu xảy ra lỗi thì lên cell tải pillow tải lại nhé!
!python trainic15data.py

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
region (1:757,1555:1555) warped shape (1024,1024)
region (1:758,1555:1555) warped shape (1024,1024)
region (1:758,1555:1555) warped shape (1024,1024)
region (6:766,1555:1555) warped shape (1024,1024)
region (6:766,1555:1555) warped shape (1024,1024)
region (8:767,1555:1555) warped shape (1024,1024)
region (8:767,1555:1555) warped shape (1024,1024)
region (8:767,1555:1555) warped shape (1024,1024)
region (3:763,1555:1555) warped shape (1024,1024)
region (3:763,1555:1555) warped shape (1024,1024)
region (3:763,1555:1555) warped shape (1024,1024)
region (3:763,1555:1555) warped shape (1024,1024)
region (6:766,1555:1555) warped shape (1024,1024)
region (6:766,1555:1555) warped shape (1024,1024)
region (777:777,13:1556) warped shape (1024,1024)
region (777:777,1555:1555) warped shape (1024,1024)
region (777:777,1555:1555) warped shape (1024,1024)
region (777:777,1555:1555) warped shape (1024,1024)
region (777:777,1555:1555) warped sha

##Test

In [ ]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [ ]:
#taỉ test data va giải nén chúng
!gdown --id 14Wf3YMoXT9LcOQWaJbRd3Or2pXMUHO3C -O test.zip
!unzip test.zip

Downloading...
From: https://drive.google.com/uc?id=14Wf3YMoXT9LcOQWaJbRd3Or2pXMUHO3C
To: /content/drive/MyDrive/CRAFT/result/test.zip
326MB [00:02, 153MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 61, in main
    quiet=args.quiet,
  File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 109, in download
    shutil.copy(tmp_file, output)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 98, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt
Archive:  test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  th

In [ ]:
#Truy cập vào file results
%cd /content/drive/MyDrive/CRAFT/results

/content/drive/MyDrive/CRAFT/results


In [ ]:
#Cài đặt một số thứ hữu ích :))
!gdown --id 1-RM4shR-oj0cWO-9mthKZKnyF-qy1OZW

Downloading...
From: https://drive.google.com/uc?id=1-RM4shR-oj0cWO-9mthKZKnyF-qy1OZW
To: /content/drive/MyDrive/CRAFT/results/CRAFT_clr_18.pth
83.2MB [00:01, 65.7MB/s]


In [ ]:
#Vào thư mục CRAFT, again :))
%cd /content/drive/MyDrive/CRAFT

/content/drive/MyDrive/CRAFT


In [ ]:
#Tiến hành test dữ liệu
!python test.py

Loading weights from checkpoint /content/drive/MyDrive/CRAFT/results/CRAFT_clr_82.pth
elapsed time : 1081.1709682941437s


In [ ]:
#Thay đổi định dạng file test
import os
%cd /content/drive/MyDrive/CRAFT/tested_image
directory = os.listdir('/content/drive/MyDrive/CRAFT/tested_image')
count = 0
text_file = open("aaaa.txt","a")
for file in directory:
	if file.endswith(".txt"):
		count = count + 1
		with open(file) as f:
			content = f.readlines()
# Xóa bỏ các khoảng trăng hoặc các ký hiệu \n tại điểm cuối mỗi dòng
		content = [x.strip() for x in content] 
		for i in range(len(content)) :
			text_file.write("{0},{1}\n".format(file,content[i]))
   
print(count)

/content/drive/MyDrive/CRAFT/tested_image
987


In [ ]:
%cd /content/drive/MyDrive/CRAFT/result
with open('/content/drive/MyDrive/CRAFT/tested_image/aaaa.txt') as f:
  contents = f.readlines()
# Xóa bỏ các khoảng trăng hoặc các ký hiệu '\n' tại điểm cuối mỗi dòng
contents = [x.strip() for x in contents] 
# Xử lý các file cho đúng định dạng để đưa vào file test.txt
for i in range(len(contents)):
  line = contents[i].split(',')
  file_name = line[0]
  line[0] = file_name[4:-4] + ".jpg"
  text_file = open('test.txt', "a")
  text_file.write("{0},{1},{2},{3},{4},{5},{6},{7},{8}\n".format(line[0],line[1],line[2],line[3],line[4],line[5],line[6],line[7],line[8]))

/content/drive/MyDrive/CRAFT/result


In [ ]:
#Xóa file aaaa.txt cho đúng định dạng nộp bài
!rm /content/drive/MyDrive/CRAFT/tested_image/aaaa.txt

rm: cannot remove '/content/drive/MyDrive/CRAFT/tested_image/aaaa.txt': No such file or directory


In [1]:
import numpy as np
A = np.zeros([5,5])
A = np.array([[3/5,0,0,1/5,1/5],
    [0,1,0,0,0],
    [0,1/5,4/5,0,0],
    [0,0,0,1,0],
    [0,0,0,1/5,4/5]])
B = np.zeros([5,5])
B = np.array([[0,1,1,0,1],
             [1,0,0,0,0],
             [1,0,0,1,0],[0,1,0,0,0],[0,1,0,0,1]])
C = np.linalg.inv(B)
D = np.zeros([5,5])
D = np.array([[1,0,0,0,0],
    [0,1,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]])
E = np.zeros([5,5])
E = B.dot(A).dot(C)
print(E)

[[ 0.8 -0.2  0.2  0.4  0. ]
 [ 0.   0.4  0.2 -0.2  0.2]
 [ 0.  -0.6  1.2 -0.2  0.2]
 [ 0.   0.   0.   1.   0. ]
 [ 0.  -0.2  0.2  0.2  0.8]]


##Submission

In [ ]:
import math, requests

def submit_prediction(df, comment='', **kwargs):
    TOKEN='501a9d24106279a6d75b5fa141e419ee66cc178b9f21147773493425bba170dfe99b5256ea6a9fcdde8b76583abfb5e973a555e31a8396a0db8d0be95340cc02'
    URL='http://submission.mmlab.uit.edu.vn/api/submissions'
    r = requests.post(URL, headers={'Authorization': 'Bearer {}'.format(TOKEN)},files={'datafile': open(df, 'rb')},data={'comment':comment})
    if r.status_code == 429:
        raise Exception('Submissions are too close. Next submission is only allowed in {} seconds.'.format(int(math.ceil(int(r.headers['x-rate-limit-remaining']) / 1000.0))))
    if r.status_code != 200:
        raise Exception(r.text)
        
submit_prediction('/content/drive/MyDrive/CRAFT/result/test.txt', comment='my submission')